language: ruby
rvm:
  - 1.9.3
services:
  - mongodb
  - elasticsearch
before_install:
  - gem update bundler
  - sudo apt-get install libicu-dev
  - cp config/envelope.example.yml config/envelope.yml
script:
  - bundle exec rspec --fail-fast
branches:
  only:
    - master
    - production
