language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
services:
  - mongodb
  - elasticsearch
before_install:
  - gem update bundler
  - sudo apt-get install -y -qq libicu-dev
  - cp config/application.example.yml config/application.yml
script:
  - bundle exec rspec --color
matrix:
  allow_failures:
    rvm:
      - 2.0.0
branches:
  only:
    - master
    - production
