language: ruby
rvm:
  - 1.9.3
services:
  - mongodb
  - elasticsearch
before_install:
  - gem update bundler
  - cp config/envelope.example.yml config/envelope.yml
script:
  - bundle exec rspec --fail-fast
