development:
  adapter: mysql2
  encoding: utf8
  database: envelope_development
  username: envelope
  password: envelope
  wait_timeout: 2147483

production:
  adapter: mysql2
  encoding: utf8
  database: envelope_production
  username: envelope
  password: envelope

test:
  adapter: mysql2
  encoding: utf8
  database: envelope_test
  username: root