development:
  adapter: mysql2
  encoding: utf8
  database: envelope_development
  username: envelope
  password: envelope
  host: 127.0.0.1
  wait_timeout: 2147483

test:
  adapter: mysql2
  encoding: utf8
  database: envelope_test
  username: envelope
  password: envelope
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: envelope_production
  username: envelope
  password: envelope
  host: 127.0.0.1