development:
  encryption_key: YOUR_KEY_HERE
  pusher:
    app_id: YOUR_APP_ID
    key: YOUR_KEY
    secret: YOUR_SECRET

production:
  encryption_key: YOUR_KEY_HERE
  pusher:
    # If you're using Heroku, uncomment this line
    # heroku: true

    # If you're not on Heroku, you'll need to add credentials
    app_id: YOUR_APP_ID
    key: YOUR_KEY
    secret: YOUR_SECRET

test:
  encryption_key: ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff
